version: "3.9"

services:
  db:
    image: postgres:16
    container_name: notes-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: notes
      POSTGRES_PASSWORD: notes
      POSTGRES_DB: notesdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notes -d notesdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin: #UI for DB
    image: dpage/pgadmin4
    container_name: notes-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@notes.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db
  backend:
    build: ./notes-backend
    container_name: notes-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  pgdata:
