spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notesdb
    username: notes
    password: notes
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5432/notesdb
    username: notes
    password: notes
